apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2022-12-13T11:00:15Z"
  generateName: vault-7f54bbc56c-
  labels:
    app: vault
    pod-template-hash: 7f54bbc56c
  name: vault-7f54bbc56c-xwksq
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: vault-7f54bbc56c
    uid: 6763b147-3e64-409c-b4d9-f88843c6f8be
  resourceVersion: "6962"
  uid: d40012eb-a5b0-4420-9bbd-26a3e7f70b75
spec:
  containers:
  - image: vault
    imagePullPolicy: Always
    name: vault
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-bdrjz
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: minikube
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-bdrjz
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-12-13T11:00:15Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2022-12-18T15:37:21Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2022-12-18T15:37:21Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2022-12-13T11:00:15Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://3f04c1c1fadb5f51ef1885c6d0a1fb94584a9699d66dfc13a3668bbe01a74f36
    image: vault:latest
    imageID: docker-pullable://vault@sha256:403c4cdc39091f58dd804133b8f1f3cc933e1a3929bd64eab50443d4557e3ee8
    lastState:
      terminated:
        containerID: docker://09a4ef58009c2ff349de5f8dc7cc470c744f947d9949258d01c38cece7134fc7
        exitCode: 255
        finishedAt: "2022-12-18T15:36:50Z"
        reason: Error
        startedAt: "2022-12-13T11:01:22Z"
    name: vault
    ready: true
    restartCount: 1
    started: true
    state:
      running:
        startedAt: "2022-12-18T15:37:20Z"
  hostIP: 192.168.49.2
  phase: Running
  podIP: 172.17.0.5
  podIPs:
  - ip: 172.17.0.5
  qosClass: BestEffort
  startTime: "2022-12-13T11:00:15Z"